# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: sky

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Jan Friedrich (Mathematics) - personal webpage - publications, conferences, teaching, short cv.'
    twitter: 'GetResearchDev'
    og_title: "Jan Friedrich - Personal Webpage"
    og_description: 'My personal webpage - publications, conferences, teaching, short cv.'
  structured_data:
    type: "Person"
    name: "Jan Friedrich"
    url: "https://janfrie-dev.github.io/home/"
    sameAs:
        - "https://github.com/janfrie-dev"
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: 'D7k1BjfzKSIAQNk2otEuxOUkPJc0luzMLG6wfvtpIkQ'
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: true
    logo:
      text: "Dr. Jan Friedrich"

# Site footer
footer:
  copyright:
    notice: '© {year} Jan Friedrich. Room 03.06.055. Technical University of Munich. School of Computation, Information and Technology Department of Mathematics. Boltzmannstraße 3, 85748 Garching b. Munich, Germany.'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false